### ISSUE TITLE
Development TODO

### ISSUE THREAD

**Issue by lucydot** [lucydot/ChooChoo#36]
### Core

- [ ] How to handle testing? 
- [ ] Think about how choochoo will integrate into an existing course repo rather than being in a standalone repo. Integration may lead to less functionality - for example, may not have an associated gh_pages branch.
- [ ] Use yaml + python dictionaries to do the many:many mapping between objectives and questions? OR play around with a mysql database which would be fun but prob overkill
- [x] separate out the choochoo repo from the project repo. Install choochoo in the repo. This separates out what a choochoo admin and what a choochoo developer needs. There will then be the choochoo repo, the choochoo-template repo and the choochoo-physics repo and so on.
- [x] whenever anything is committed to main in questions, tutorials or proposed_questions then automatically compile into html on gh-pages (jekyll, markdown or pandoc type thing?)
- [ ] Stop students from creating more than one checklist per person

### Improvements

- [ ] allow parsing of multiple usernames in the CLI. Allow multiple users to be added as students, instructors etc: so instead of finding handles by positions, search by words starting with @ and then form into a list of strings. Regex will do this task quite nicely!
- [ ] the cli is clunky: perhaps use switch instead (Python 3.9+ only). Or create my own simple parser (command class).
- [ ] Choochoo returns update messages when something succesfully done
- [ ] Assign the issues to appropriate people (the people who raised them?)
